[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
  "ruff>=0.5",
  "pyright>=1.1",
  "pytest>=8",
  "pytest-cov>=5",
  "mkdocs-material>=9.5",
]

[tool.uv.workspace]
members = ["packages/gs-schema", "packages/gs-env", "packages/gs-agent"]
