[project]
name = "gs-env"
version = "0.1.0"
requires-python = ">=3.10"
description = "Genesis-based environments"
dependencies = ["gs-schema>=0.1.0"]

[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"
